


[general]
import = [
  "~/.config/alacritty/themes/themes/coolnight.toml",
  "~/.config/alacritty/alacritty.config/window.alacritty.toml",
  "~/.config/alacritty/alacritty.config/env.alacritty.toml",
  "~/.config/alacritty/alacritty.config/font.alacritty.toml",
  "~/.config/alacritty/alacritty.config/cursor.alacritty.toml"
]
