AT_LOGIN_APPS=(
    "/Applications/Hot.app"
    "/Applications/Raycast.app"
    "/Applications/BetterDisplay.app"
    "/Applications/KeyClu.app"
    "/Applications/Shottr.app"
    "/Applications/Clop.app"
    "/Applications/Amphetamine.app"
)
