AT_LOGIN_APPS=(
    "/Applications/Hot.app"
    "/Applications/Raycast.app"
    "/Applications/KeyClu.app"
    "/Applications/Shottr.app"
    "/Applications/Clop.app"
    "/Applications/Caffeine.app"
    "/Applications/LinearMouse.app"
    "/Applications/AltTab.app"
)