"use strict";var A=Object.create;var p=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var F=Object.getOwnPropertyNames;var k=Object.getPrototypeOf,P=Object.prototype.hasOwnProperty;var N=(e,o)=>{for(var t in o)p(e,t,{get:o[t],enumerable:!0})},g=(e,o,t,n)=>{if(o&&typeof o=="object"||typeof o=="function")for(let i of F(o))!P.call(e,i)&&i!==t&&p(e,i,{get:()=>o[i],enumerable:!(n=v(o,i))||n.enumerable});return e};var L=(e,o,t)=>(t=e!=null?A(k(e)):{},g(o||!e||!e.__esModule?p(t,"default",{value:e,enumerable:!0}):t,e)),O=e=>g(p({},"__esModule",{value:!0}),e);var D={};N(D,{default:()=>b});module.exports=O(D);var r=require("@raycast/api");var h=require("node:crypto");var C="useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict";var T=128,c,l;function U(e){!c||c.length<e?(c=Buffer.allocUnsafe(e*T),h.webcrypto.getRandomValues(c),l=0):l+e>c.length&&(h.webcrypto.getRandomValues(c),l=0),l+=e}function H(e=21){U(e|=0);let o="";for(let t=l-e;t<l;t++)o+=C[c[t]&63];return o}var d=require("@raycast/api"),f=L(require("fs")),K=(0,d.getPreferenceValues)(),u=K.sshConfig.replace("~",process.env.HOME);function R(e){let t=f.readFileSync(e,"utf8").split(`
`),n=[],i=null;for(let y of t){let a=y.trim();if(!(a.startsWith("#")||a==="")){if(a.startsWith("Host ")&&a!=="Host *")i!==null&&n.push(i),i={id:n.length.toString(),address:"",name:a.substring(5),user:""};else if(i!==null){let S=a.indexOf(" "),w=a.substring(0,S),m=a.substring(S+1);switch(w){case"HostName":i.address=m;break;case"User":i.user=m;break;case"Port":i.port=m;break;case"IdentityFile":i.sshKey=m;break;case"HostNameKey":break;case"RemoteCommand":i.command=m;break;default:break}}}}return i!==null&&n.push(i),n}function $(e,o){let t="";for(let n of o)t+=`Host ${n.name}
`,t+=`  HostName ${n.address}
`,n.user&&(t+=`  User ${n.user}
`),n.port&&(t+=`  Port ${n.port}
`),n.sshKey&&(t+=`  IdentityFile ${n.sshKey}
`),n.command&&(t+=`  RemoteCommand ${n.command}
`),t+=`
`;f.writeFileSync(e,t.trimEnd())}async function x(){switch(u){case"localStorage":{let{connections:e}=await d.LocalStorage.allItems();return e?JSON.parse(e):[]}default:return f.existsSync(u)?R(u):[]}}async function I(e){switch(u){case"localStorage":await d.LocalStorage.setItem("connections",JSON.stringify(e));break;default:$(u,e);break}}var s=require("react/jsx-runtime");function b(){let{pop:e}=(0,r.useNavigation)();async function o(t){let n=await x();n.push({...t,id:H()}),await I(n),await(0,r.showHUD)(`\u2705 Connection [${t.name}] saved!`),e()}return(0,s.jsxs)(r.Form,{actions:(0,s.jsx)(r.ActionPanel,{children:(0,s.jsx)(r.Action.SubmitForm,{title:"Save",onSubmit:t=>o(t)})}),children:[(0,s.jsx)(r.Form.TextField,{id:"name",title:"Connection Name"}),(0,s.jsx)(r.Form.TextField,{id:"address",title:"Server Address",placeholder:"A resolvable DNS name or IP"}),(0,s.jsx)(r.Form.TextField,{id:"user",title:"Username (optional)",placeholder:"A username to authenticate with"}),(0,s.jsx)(r.Form.TextField,{id:"port",title:"Port (optional)",placeholder:"An optional custom port (other than 22)"}),(0,s.jsx)(r.Form.TextField,{id:"sshKey",title:"SSH Key Location (optional)",placeholder:"An optional key path to authenticate with"}),(0,s.jsx)(r.Form.TextField,{id:"command",title:"Command to Execute (optional)",placeholder:"An optional command to execute on the remote server after connecting"})]})}
